name: generate animation

on:
  schedule:
    - cron: "0 */12 * * *" 
  
  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Tworzenie katalogu wyjściowego
      - name: Create output directory
        run: mkdir -p dist

      # Generowanie animacji
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3.0.0
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Sprawdzenie zawartości katalogu dist (do debugowania)
      - name: Check dist folder content
        run: ls -la dist

      # Publikowanie animacji
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
